### 1-Library

In [5]:
from pathlib import Path

import duckdb
import pandas as pd


print(f"DuckDB: {duckdb.__version__}")

DuckDB: 1.4.5

### 2.localizar o CSV

In [6]:
PROJECT_ROOT = Path.cwd()

if PROJECT_ROOT.name == "notebook":
    PROJECT_ROOT = PROJECT_ROOT.parent

ano_teste = 1998

arquivo_csv = (
    PROJECT_ROOT
    / "data"
    / "staging"
    / f"ano_{ano_teste}"
    / f"MICRODADOS_ENEM_{ano_teste}.csv"
)

if not arquivo_csv.exists():
    raise FileNotFoundError(
        f"CSV não encontrado: {arquivo_csv}"
    )

print(f"Arquivo: {arquivo_csv}")
print(
    f"Tamanho: "
    f"{arquivo_csv.stat().st_size / 1024**2:.2f} MB"
)

Arquivo: /home/akel/PycharmProjects/ENEM/data/staging/ano_1998/MICRODADOS_ENEM_1998.csv
Tamanho: 60.14 MB

### 3. criar conexão em memória

In [7]:
conexao = duckdb.connect()

print("Conexão DuckDB criada em memória.")

Conexão DuckDB criada em memória.

### 4. ler somente cinco registros

In [8]:
caminho_sql = str(arquivo_csv).replace("'", "''")

consulta_amostra = f"""
SELECT *
FROM read_csv(
    '{caminho_sql}',
    delim = ';',
    header = true,
    all_varchar = true
)
LIMIT 5
"""

amostra = conexao.execute(
    consulta_amostra
).df()

amostra

,NU_INSCRICAO,NU_ANO,TP_FAIXA_ETARIA,TP_SEXO,CO_MUNICIPIO_RESIDENCIA,NO_MUNICIPIO_RESIDENCIA,CO_UF_RESIDENCIA,SG_UF_RESIDENCIA,TP_PRESENCA,CO_PROVA,...,Q128,Q129,Q130,Q131,Q132,Q133,Q134,Q135,Q136,Q137
0,1,1998,4,F,2408003,MOSSORO,24,RN,1,B,...,A,B,A,B,B,B,B,B,B,B
1,2,1998,2,F,2401453,BARAUNA,24,RN,1,B,...,B,B,A,A,B,C,A,A,A,A
2,3,1998,3,M,2408003,MOSSORO,24,RN,1,Z,...,A,A,A,A,C,C,C,C,C,C
3,4,1998,3,M,2408003,MOSSORO,24,RN,1,G,...,B,B,A,A,C,C,B,B,B,B
4,5,1998,6,M,2413102,SENADOR ELOI DE SOUZA,24,RN,1,A,...,A,A,A,A,B,C,B,B,B,B

### 5.verificar dimensões da amostra

In [5]:
print(f"Linhas carregadas: {amostra.shape[0]}")
print(f"Colunas encontradas: {amostra.shape[1]}")

Linhas carregadas: 5
Colunas encontradas: 163

### 6.listar as colunas

In [6]:
# for numero, coluna in enumerate(
#     amostra.columns,
#     start=1,
# ):
#     print(f"{numero:02d} - {coluna}")

### 7.localizar o catálogo

In [7]:
arquivo_catalogo = (
    PROJECT_ROOT
    / "data"
    / "metadata"
    / "dicionarios"
    / "variaveis_enem_por_ano.csv"
)

if not arquivo_catalogo.exists():
    raise FileNotFoundError(
        f"Catálogo não encontrado: {arquivo_catalogo}"
    )

print(f"Catálogo: {arquivo_catalogo}")

Catálogo: /home/akel/PycharmProjects/ENEM/data/metadata/dicionarios/variaveis_enem_por_ano.csv

### 8.carregar o catálogo

In [8]:
catalogo = pd.read_csv(
    arquivo_catalogo,
    sep=",",
    dtype="string",
)

print(f"Anos no catálogo: {catalogo.shape[1]}")
print(f"Linhas no catálogo: {catalogo.shape[0]}")

catalogo.head()

Anos no catálogo: 28
Linhas no catálogo: 54

,1998,1999,2000,2001,2002,2003,2004,2005,2006,2007,...,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025
0,NU_INSCRICAO,NU_INSCRICAO,NU_INSCRICAO,NU_INSCRICAO,NU_INSCRICAO,NU_INSCRICAO,NU_INSCRICAO,NU_INSCRICAO,NU_INSCRICAO,NU_INSCRICAO,...,NU_INSCRICAO,NU_INSCRICAO,NU_INSCRICAO,NU_INSCRICAO,NU_INSCRICAO,NU_INSCRICAO,NU_INSCRICAO,NU_INSCRICAO,NU_INSCRICAO,NU_INSCRICAO
1,NU_ANO,NU_ANO,NU_ANO,NU_ANO,NU_ANO,TP_FAIXA_ETARIA,NU_ANO,NU_ANO,NU_ANO,NU_ANO,...,NU_ANO,NU_ANO,NU_ANO,NU_ANO,NU_ANO,NU_ANO,NU_ANO,NU_ANO,NU_ANO,NU_ANO
2,TP_FAIXA_ETARIA,TP_FAIXA_ETARIA,TP_FAIXA_ETARIA,TP_FAIXA_ETARIA,TP_FAIXA_ETARIA,TP_SEXO,TP_FAIXA_ETARIA,TP_FAIXA_ETARIA,TP_FAIXA_ETARIA,TP_FAIXA_ETARIA,...,TP_FAIXA_ETARIA,TP_FAIXA_ETARIA,TP_FAIXA_ETARIA,TP_FAIXA_ETARIA,TP_FAIXA_ETARIA,TP_FAIXA_ETARIA,TP_FAIXA_ETARIA,TP_FAIXA_ETARIA,TP_FAIXA_ETARIA,TP_FAIXA_ETARIA
3,TP_SEXO,TP_SEXO,TP_SEXO,TP_SEXO,TP_SEXO,CO_MUNICIPIO_RESIDENCIA,TP_SEXO,TP_SEXO,TP_SEXO,TP_SEXO,...,TP_SEXO,TP_SEXO,TP_SEXO,TP_SEXO,TP_SEXO,TP_SEXO,TP_SEXO,TP_SEXO,TP_SEXO,TP_SEXO
4,CO_MUNICIPIO_RESIDENCIA,CO_MUNICIPIO_RESIDENCIA,CO_MUNICIPIO_RESIDENCIA,CO_MUNICIPIO_RESIDENCIA,CO_MUNICIPIO_RESIDENCIA,NO_MUNICIPIO_RESIDENCIA,CO_MUNICIPIO_RESIDENCIA,CO_MUNICIPIO_RESIDENCIA,CO_MUNICIPIO_RESIDENCIA,CO_MUNICIPIO_RESIDENCIA,...,TP_ESTADO_CIVIL,TP_ESTADO_CIVIL,TP_ESTADO_CIVIL,TP_ESTADO_CIVIL,TP_ESTADO_CIVIL,TP_ESTADO_CIVIL,TP_ESTADO_CIVIL,TP_ESTADO_CIVIL,TP_ESTADO_CIVIL,TP_ESTADO_CIVIL

### 9.obter as variáveis de 1998

In [9]:
def obter_variaveis_ano(
    catalogo: pd.DataFrame,
    ano: int,
) -> list[str]:
    """
    Retorna as variáveis selecionadas para determinado ano,
    excluindo células vazias e títulos de seção.
    """
    coluna_ano = str(ano)

    if coluna_ano not in catalogo.columns:
        raise KeyError(
            f"O ano {ano} não existe no catálogo."
        )

    valores = (
        catalogo[coluna_ano]
        .dropna()
        .str.strip()
        .tolist()
    )

    variaveis = []

    for valor in valores:
        if not valor:
            continue

        if valor.upper().startswith("VARIÁVEIS "):
            continue

        if valor.lower() == "nome da variável":
            continue

        variaveis.append(valor)

    return variaveis

In [10]:
variaveis_1998 = obter_variaveis_ano(
    catalogo=catalogo,
    ano=ano_teste,
)

print(
    f"Variáveis selecionadas para {ano_teste}: "
    f"{len(variaveis_1998)}"
)

for numero, variavel in enumerate(
    variaveis_1998,
    start=1,
):
    print(f"{numero:02d} - {variavel}")

Variáveis selecionadas para 1998: 25
01 - NU_INSCRICAO
02 - NU_ANO
03 - TP_FAIXA_ETARIA
04 - TP_SEXO
05 - CO_MUNICIPIO_RESIDENCIA
06 - NO_MUNICIPIO_RESIDENCIA
07 - CO_UF_RESIDENCIA
08 - SG_UF_RESIDENCIA
09 - TP_PRESENCA
10 - CO_PROVA
11 - VL_PERC_COMP1
12 - VL_PERC_COMP2
13 - VL_PERC_COMP3
14 - VL_PERC_COMP4
15 - VL_PERC_COMP5
16 - NU_NOTA_OBJETIVA
17 - TX_RESPOSTAS_OBJETIVA
18 - TX_GABARITO_OBJETIVA
19 - TP_STATUS_REDACAO
20 - NU_NOTA_COMP1
21 - NU_NOTA_COMP2
22 - NU_NOTA_COMP3
23 - NU_NOTA_COMP4
24 - NU_NOTA_COMP5
25 - NU_NOTA_REDACAO

### 10 — comparar catálogo e CSV

In [11]:
colunas_csv = set(amostra.columns)
colunas_catalogo = set(variaveis_1998)

variaveis_ausentes = sorted(
    colunas_catalogo - colunas_csv
)

variaveis_nao_selecionadas = sorted(
    colunas_csv - colunas_catalogo
)

print(
    f"Colunas no CSV: "
    f"{len(colunas_csv)}"
)

print(
    f"Variáveis selecionadas: "
    f"{len(colunas_catalogo)}"
)

print(
    f"Variáveis ausentes no CSV: "
    f"{len(variaveis_ausentes)}"
)

print(
    f"Colunas que serão descartadas: "
    f"{len(variaveis_nao_selecionadas)}"
)

#----------------------------
if variaveis_ausentes:
    print("Variáveis selecionadas que não existem no CSV:")

    for variavel in variaveis_ausentes:
        print(f"- {variavel}")
else:
    print(
        "Todas as variáveis selecionadas "
        "existem no CSV."
    )

Colunas no CSV: 163
Variáveis selecionadas: 25
Variáveis ausentes no CSV: 0
Colunas que serão descartadas: 138
Todas as variáveis selecionadas existem no CSV.

### 11 — criar a seleção SQL

In [12]:
def citar_identificador(nome: str) -> str:
    """
    Protege nomes de colunas para uso em SQL.
    """
    return '"' + nome.replace('"', '""') + '"'


colunas_sql = ",\n    ".join(
    citar_identificador(variavel)
    for variavel in variaveis_1998
)

print(colunas_sql)

"NU_INSCRICAO",
    "NU_ANO",
    "TP_FAIXA_ETARIA",
    "TP_SEXO",
    "CO_MUNICIPIO_RESIDENCIA",
    "NO_MUNICIPIO_RESIDENCIA",
    "CO_UF_RESIDENCIA",
    "SG_UF_RESIDENCIA",
    "TP_PRESENCA",
    "CO_PROVA",
    "VL_PERC_COMP1",
    "VL_PERC_COMP2",
    "VL_PERC_COMP3",
    "VL_PERC_COMP4",
    "VL_PERC_COMP5",
    "NU_NOTA_OBJETIVA",
    "TX_RESPOSTAS_OBJETIVA",
    "TX_GABARITO_OBJETIVA",
    "TP_STATUS_REDACAO",
    "NU_NOTA_COMP1",
    "NU_NOTA_COMP2",
    "NU_NOTA_COMP3",
    "NU_NOTA_COMP4",
    "NU_NOTA_COMP5",
    "NU_NOTA_REDACAO"

### 12 — filtrar o Pará

In [13]:
consulta_para = f"""
SELECT
    {colunas_sql}
FROM read_csv(
    '{caminho_sql}',
    delim = ';',
    header = true,
    all_varchar = true
)
WHERE SG_UF_RESIDENCIA = 'PA'

"""

amostra_para = conexao.execute(
    consulta_para
).df()

amostra_para

,NU_INSCRICAO,NU_ANO,TP_FAIXA_ETARIA,TP_SEXO,CO_MUNICIPIO_RESIDENCIA,NO_MUNICIPIO_RESIDENCIA,CO_UF_RESIDENCIA,SG_UF_RESIDENCIA,TP_PRESENCA,CO_PROVA,...,NU_NOTA_OBJETIVA,TX_RESPOSTAS_OBJETIVA,TX_GABARITO_OBJETIVA,TP_STATUS_REDACAO,NU_NOTA_COMP1,NU_NOTA_COMP2,NU_NOTA_COMP3,NU_NOTA_COMP4,NU_NOTA_COMP5,NU_NOTA_REDACAO
0,308,1998,2,F,1505502,PARAGOMINAS,15,PA,1,A,...,38.1,CCBABBDBDABCACDCEEDACEBCBAABBDECDABAEDCCCDDACB...,CDBEBDAADBBEDDDEAECBABCABBCACADABABCEBCECDDDAB...,P,45,15,15,0,0,75
1,309,1998,1,M,1501402,BELEM,15,PA,1,B,...,77.8,BEACDCEBBABBCBCDECABEBDEADDDBDCBBEADDDEDACCEBE...,BECDDCEDBABBCBCDECABECDEADBABACBBEADDDADADCEBE...,P,60,20,20,0,0,100
2,310,1998,3,F,1501402,BELEM,15,PA,1,A,...,42.9,EEBEBCABBABCBCEDEEBDDBAAEBCACADADBCEEDCCDDABCE...,CDBEBDAADBBEDDDEAECBABCABBCACADABABCEBCECDDDAB...,P,45,20,15,0,0,80
3,311,1998,2,F,1501402,BELEM,15,PA,1,A,...,44.4,EDCEBBABCDBECDDBAEDBDBDDDADADCDEBCBDEBDBDBBDAC...,CDBEBDAADBBEDDDEAECBABCABBCACADABABCEBCECDDDAB...,P,60,20,20,0,0,100
4,312,1998,2,M,1501402,BELEM,15,PA,1,Z,...,36.5,ABBCDDCCBCDABAEAABACBAEEBCDBECABBCADBEDDABCDEA...,DABEDADDCECBEBBBCBACBDEECADBADADDBADCEBEABCDBC...,P,0,5,5,0,0,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
283,10804,1998,3,F,1505502,PARAGOMINAS,15,PA,1,Z,...,28.6,ABDDEDCEAEBBEBECAAEAEDBEDCAAEADBDBEDCEDEAEEEBA...,DABEDADDCECBEBBBCBACBDEECADBADADDBADCEBEABCDBC...,P,15,0,5,0,0,20
284,10805,1998,3,M,1501402,BELEM,15,PA,1,B,...,27,CEEABBABCBBCACDEAEAADBDDDBAABADBECCDEBCBCDDDAD...,BECDDCEDBABBCBCDECABECDEADBABACBBEADDDADADCEBE...,P,15,0,5,0,0,20
285,10806,1998,2,M,1501402,BELEM,15,PA,1,G,...,65.1,DAAEBDCBACDCEBEDBBAACDDECCCEDBEEBDABBABEEDDAAE...,DAACDDCBACDCEAEDBBBBCCDEBACECBEDBAABACBBEDDADA...,P,60,15,15,0,0,90
286,10807,1998,5,M,1505502,PARAGOMINAS,15,PA,1,B,...,47.6,BCDDDDDABBBBCEABDCCEEBDEAEBCBBABBBDCDDDABDCEBE...,BECDDCEDBABBCBCDECABECDEADBABACBBEADDDADADCEBE...,P,15,10,5,0,0,30
287,10808,1998,4,M,1501402,BELEM,15,PA,0,None,...,0,None,None,F,0,0,0,0,0,0

### 13 — validar a amostra do Pará

In [14]:
print(f"Linhas: {amostra_para.shape[0]}")
print(f"Colunas: {amostra_para.shape[1]}")

print(
    "UFs encontradas:",
    amostra_para["SG_UF_RESIDENCIA"]
    .unique()
    .tolist(),
)

Linhas: 288
Colunas: 25
UFs encontradas: ['PA']

### 14 — validar a amostra do Pará

In [15]:
conexao.execute(
    f"""
    CREATE OR REPLACE TEMP VIEW enem_1998_raw AS

    SELECT *
    FROM read_csv(
        '{caminho_sql}',
        delim = ';',
        header = true,
        all_varchar = true
    )
    """
)

print("View temporária criada.")

View temporária criada.

### 15 — contar registros

In [16]:
contagem = conexao.execute(
    """
    SELECT
        COUNT(*) AS total_brasil,

        COUNT(*) FILTER (
            WHERE SG_UF_RESIDENCIA = 'PA'
        ) AS total_para,

        COUNT(*) FILTER (
            WHERE SG_UF_RESIDENCIA IS NULL
               OR TRIM(SG_UF_RESIDENCIA) = ''
        ) AS total_sem_uf

    FROM enem_1998_raw
    """
).df()

contagem

   total_brasil  total_para  total_sem_uf
0        150944         288             0

In [17]:
contagem["percentual_para"] = (
    contagem["total_para"]
    / contagem["total_brasil"]
    * 100
)

contagem

   total_brasil  total_para  total_sem_uf  percentual_para
0        150944         288             0         0.190799

### 16 — distribuição por UF

In [18]:
distribuicao_uf = conexao.execute(
    """
    SELECT
        SG_UF_RESIDENCIA AS uf,
        COUNT(*) AS quantidade

    FROM enem_1998_raw

    GROUP BY SG_UF_RESIDENCIA
    ORDER BY quantidade DESC
    """
).df()

distribuicao_uf

    uf  quantidade
0   PR       53722
1   RJ       36908
2   MG       23412
3   PE       10295
4   SP        8845
5   RN        4492
6   ES        3013
7   MT        1726
8   SC        1313
9   MS        1159
10  RS         997
11  RR         967
12  CE         667
13  AC         570
14  GO         479
15  AM         456
16  SE         344
17  PB         303
18  PA         288
19  DF         243
20  BA         180
21  AL         166
22  RO         111
23  PI         103
24  MA          90
25  TO          48
26  AP          47

### 17 — verificar duplicações da inscrição no Pará

In [19]:
duplicacoes = conexao.execute(
    """
    SELECT
        COUNT(*) AS total_linhas,
        COUNT(DISTINCT NU_INSCRICAO) AS inscricoes_unicas,
        COUNT(*) - COUNT(DISTINCT NU_INSCRICAO) AS duplicacoes

    FROM enem_1998_raw

    WHERE SG_UF_RESIDENCIA = 'PA'
    """
).df()

duplicacoes

   total_linhas  inscricoes_unicas  duplicacoes
0           288                288            0

### 18. Definir Grupo de Variaveis

In [20]:

variaveis_numericas = [
    "NU_ANO",
    "TP_FAIXA_ETARIA",
    "TP_PRESENCA",
    "VL_PERC_COMP1",
    "VL_PERC_COMP2",
    "VL_PERC_COMP3",
    "VL_PERC_COMP4",
    "VL_PERC_COMP5",
    "NU_NOTA_OBJETIVA",
    "NU_NOTA_COMP1",
    "NU_NOTA_COMP2",
    "NU_NOTA_COMP3",
    "NU_NOTA_COMP4",
    "NU_NOTA_COMP5",
    "NU_NOTA_REDACAO",
]

variaveis_texto = [
    variavel
    for variavel in variaveis_1998
    if variavel not in variaveis_numericas
]

print(f"Variáveis numéricas: {len(variaveis_numericas)}")
print(f"Variáveis de texto: {len(variaveis_texto)}")

Variáveis numéricas: 15
Variáveis de texto: 10

### 19.Buscar por  valores numéricos inválidos

In [21]:
expressoes_invalidos = []

for variavel in variaveis_numericas:
    coluna = citar_identificador(variavel)

    expressao = f"""
        SUM(
            CASE
                WHEN NULLIF(TRIM({coluna}), '') IS NOT NULL
                 AND TRY_CAST({coluna} AS DOUBLE) IS NULL
                THEN 1
                ELSE 0
            END
        ) AS {coluna}
    """

    expressoes_invalidos.append(expressao)

sql_invalidos = ",\n".join(
    expressoes_invalidos
)

consulta_invalidos = f"""
SELECT
    {sql_invalidos}

FROM enem_1998_raw

WHERE SG_UF_RESIDENCIA = 'PA'
"""

invalidos_numericos = conexao.execute(
    consulta_invalidos
).df()

invalidos_numericos

,NU_ANO,TP_FAIXA_ETARIA,TP_PRESENCA,VL_PERC_COMP1,VL_PERC_COMP2,VL_PERC_COMP3,VL_PERC_COMP4,VL_PERC_COMP5,NU_NOTA_OBJETIVA,NU_NOTA_COMP1,NU_NOTA_COMP2,NU_NOTA_COMP3,NU_NOTA_COMP4,NU_NOTA_COMP5,NU_NOTA_REDACAO
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

### 20 — transformar o resultado em formato vertical

In [22]:
invalidos_numericos_vertical = (
    invalidos_numericos
    .T
    .reset_index()
)

invalidos_numericos_vertical.columns = [
    "variavel",
    "valores_invalidos",
]

invalidos_numericos_vertical

            variavel  valores_invalidos
0             NU_ANO                0.0
1    TP_FAIXA_ETARIA                0.0
2        TP_PRESENCA                0.0
3      VL_PERC_COMP1                0.0
4      VL_PERC_COMP2                0.0
5      VL_PERC_COMP3                0.0
6      VL_PERC_COMP4                0.0
7      VL_PERC_COMP5                0.0
8   NU_NOTA_OBJETIVA                0.0
9      NU_NOTA_COMP1                0.0
10     NU_NOTA_COMP2                0.0
11     NU_NOTA_COMP3                0.0
12     NU_NOTA_COMP4                0.0
13     NU_NOTA_COMP5                0.0
14   NU_NOTA_REDACAO                0.0

### 21 — destacar problemas

In [23]:
problemas_numericos = (
    invalidos_numericos_vertical[
        invalidos_numericos_vertical[
            "valores_invalidos"
        ] > 0
    ]
)

if problemas_numericos.empty:
    print(
        "Todas as variáveis numéricas podem "
        "ser convertidas."
    )
else:
    print(
        "Existem valores que não podem ser "
        "convertidos:"
    )

    display(problemas_numericos)

Todas as variáveis numéricas podem ser convertidas.

### 22-Definir Tipos

In [25]:
variaveis_inteiras = {
    "NU_ANO",
    "TP_FAIXA_ETARIA",
    "TP_PRESENCA",
}

variaveis_decimais = {
    "VL_PERC_COMP1",
    "VL_PERC_COMP2",
    "VL_PERC_COMP3",
    "VL_PERC_COMP4",
    "VL_PERC_COMP5",
    "NU_NOTA_OBJETIVA",
    "NU_NOTA_COMP1",
    "NU_NOTA_COMP2",
    "NU_NOTA_COMP3",
    "NU_NOTA_COMP4",
    "NU_NOTA_COMP5",
    "NU_NOTA_REDACAO",
}

### 23.Construir as conversões

In [26]:
expressoes_transformacao = []

for variavel in variaveis_1998:
    coluna = citar_identificador(variavel)

    if variavel in variaveis_inteiras:
        expressao = (
            f"TRY_CAST(NULLIF(TRIM({coluna}), '') "
            f"AS SMALLINT) AS {coluna}"
        )

    elif variavel in variaveis_decimais:
        expressao = (
            f"TRY_CAST(NULLIF(TRIM({coluna}), '') "
            f"AS DOUBLE) AS {coluna}"
        )

    else:
        expressao = (
            f"NULLIF(TRIM({coluna}), '') "
            f"AS {coluna}"
        )

    expressoes_transformacao.append(expressao)

transformacoes_sql = ",\n    ".join(
    expressoes_transformacao
)

print(transformacoes_sql)

NULLIF(TRIM("NU_INSCRICAO"), '') AS "NU_INSCRICAO",
    TRY_CAST(NULLIF(TRIM("NU_ANO"), '') AS SMALLINT) AS "NU_ANO",
    TRY_CAST(NULLIF(TRIM("TP_FAIXA_ETARIA"), '') AS SMALLINT) AS "TP_FAIXA_ETARIA",
    NULLIF(TRIM("TP_SEXO"), '') AS "TP_SEXO",
    NULLIF(TRIM("CO_MUNICIPIO_RESIDENCIA"), '') AS "CO_MUNICIPIO_RESIDENCIA",
    NULLIF(TRIM("NO_MUNICIPIO_RESIDENCIA"), '') AS "NO_MUNICIPIO_RESIDENCIA",
    NULLIF(TRIM("CO_UF_RESIDENCIA"), '') AS "CO_UF_RESIDENCIA",
    NULLIF(TRIM("SG_UF_RESIDENCIA"), '') AS "SG_UF_RESIDENCIA",
    TRY_CAST(NULLIF(TRIM("TP_PRESENCA"), '') AS SMALLINT) AS "TP_PRESENCA",
    NULLIF(TRIM("CO_PROVA"), '') AS "CO_PROVA",
    TRY_CAST(NULLIF(TRIM("VL_PERC_COMP1"), '') AS DOUBLE) AS "VL_PERC_COMP1",
    TRY_CAST(NULLIF(TRIM("VL_PERC_COMP2"), '') AS DOUBLE) AS "VL_PERC_COMP2",
    TRY_CAST(NULLIF(TRIM("VL_PERC_COMP3"), '') AS DOUBLE) AS "VL_PERC_COMP3",
    TRY_CAST(NULLIF(TRIM("VL_PERC_COMP4"), '') AS DOUBLE) AS "VL_PERC_COMP4",
    TRY_CAST(NULLIF(TRIM("VL_PERC_COMP5"), '') AS DOUBLE) AS "VL_PERC_COMP5",
    TRY_CAST(NULLIF(TRIM("NU_NOTA_OBJETIVA"), '') AS DOUBLE) AS "NU_NOTA_OBJETIVA",
    NULLIF(TRIM("TX_RESPOSTAS_OBJETIVA"), '') AS "TX_RESPOSTAS_OBJETIVA",
    NULLIF(TRIM("TX_GABARITO_OBJETIVA"), '') AS "TX_GABARITO_OBJETIVA",
    NULLIF(TRIM("TP_STATUS_REDACAO"), '') AS "TP_STATUS_REDACAO",
    TRY_CAST(NULLIF(TRIM("NU_NOTA_COMP1"), '') AS DOUBLE) AS "NU_NOTA_COMP1",
    TRY_CAST(NULLIF(TRIM("NU_NOTA_COMP2"), '') AS DOUBLE) AS "NU_NOTA_COMP2",
    TRY_CAST(NULLIF(TRIM("NU_NOTA_COMP3"), '') AS DOUBLE) AS "NU_NOTA_COMP3",
    TRY_CAST(NULLIF(TRIM("NU_NOTA_COMP4"), '') AS DOUBLE) AS "NU_NOTA_COMP4",
    TRY_CAST(NULLIF(TRIM("NU_NOTA_COMP5"), '') AS DOUBLE) AS "NU_NOTA_COMP5",
    TRY_CAST(NULLIF(TRIM("NU_NOTA_REDACAO"), '') AS DOUBLE) AS "NU_NOTA_REDACAO"

### 24. Criar a view tipada do Pará

In [27]:
conexao.execute(
    f"""
    CREATE OR REPLACE TEMP VIEW enem_1998_pa_tipado AS

    SELECT
        {transformacoes_sql}

    FROM enem_1998_raw

    WHERE SG_UF_RESIDENCIA = 'PA'
    """
)

print("View tipada do Pará criada.")

View tipada do Pará criada.

### 25. Verificar os tipos resultantes

In [28]:
tipos_resultantes = conexao.execute(
    """
    DESCRIBE enem_1998_pa_tipado
    """
).df()

tipos_resultantes[
    [
        "column_name",
        "column_type",
        "null",
    ]
]

                column_name column_type null
0              NU_INSCRICAO     VARCHAR  YES
1                    NU_ANO    SMALLINT  YES
2           TP_FAIXA_ETARIA    SMALLINT  YES
3                   TP_SEXO     VARCHAR  YES
4   CO_MUNICIPIO_RESIDENCIA     VARCHAR  YES
5   NO_MUNICIPIO_RESIDENCIA     VARCHAR  YES
6          CO_UF_RESIDENCIA     VARCHAR  YES
7          SG_UF_RESIDENCIA     VARCHAR  YES
8               TP_PRESENCA    SMALLINT  YES
9                  CO_PROVA     VARCHAR  YES
10            VL_PERC_COMP1      DOUBLE  YES
11            VL_PERC_COMP2      DOUBLE  YES
12            VL_PERC_COMP3      DOUBLE  YES
13            VL_PERC_COMP4      DOUBLE  YES
14            VL_PERC_COMP5      DOUBLE  YES
15         NU_NOTA_OBJETIVA      DOUBLE  YES
16    TX_RESPOSTAS_OBJETIVA     VARCHAR  YES
17     TX_GABARITO_OBJETIVA     VARCHAR  YES
18        TP_STATUS_REDACAO     VARCHAR  YES
19            NU_NOTA_COMP1      DOUBLE  YES
20            NU_NOTA_COMP2      DOUBLE  YES
21            NU_NOTA_COMP3      DOUBLE  YES
22            NU_NOTA_COMP4      DOUBLE  YES
23            NU_NOTA_COMP5      DOUBLE  YES
24          NU_NOTA_REDACAO      DOUBLE  YES

### 26. Validar quantidade e unicidade

In [31]:
validacao_estrutura = conexao.execute(
    """
    SELECT
        COUNT(*) AS total_linhas,
        COUNT(DISTINCT NU_INSCRICAO) AS inscricoes_unicas,
        COUNT(*) - COUNT(DISTINCT NU_INSCRICAO) AS duplicacoes,
        COUNT(DISTINCT SG_UF_RESIDENCIA) AS quantidade_ufs,
        MIN(NU_ANO) AS menor_ano,
        MAX(NU_ANO) AS maior_ano

    FROM enem_1998_pa_tipado
    """
).df()

validacao_estrutura.T

                      0
total_linhas        288
inscricoes_unicas   288
duplicacoes           0
quantidade_ufs        1
menor_ano          1998
maior_ano          1998

### 27.Verificar intervalos das notas

In [30]:
intervalos_notas = conexao.execute(
    """
    SELECT
        MIN(NU_NOTA_OBJETIVA) AS minima_objetiva,
        MAX(NU_NOTA_OBJETIVA) AS maxima_objetiva,

        MIN(NU_NOTA_REDACAO) AS minima_redacao,
        MAX(NU_NOTA_REDACAO) AS maxima_redacao,

        MIN(NU_NOTA_COMP1) AS minima_comp1,
        MAX(NU_NOTA_COMP1) AS maxima_comp1,

        MIN(NU_NOTA_COMP2) AS minima_comp2,
        MAX(NU_NOTA_COMP2) AS maxima_comp2,

        MIN(NU_NOTA_COMP3) AS minima_comp3,
        MAX(NU_NOTA_COMP3) AS maxima_comp3,

        MIN(NU_NOTA_COMP4) AS minima_comp4,
        MAX(NU_NOTA_COMP4) AS maxima_comp4,

        MIN(NU_NOTA_COMP5) AS minima_comp5,
        MAX(NU_NOTA_COMP5) AS maxima_comp5

    FROM enem_1998_pa_tipado
    """
).df()

intervalos_notas.T

                     0
minima_objetiva    0.0
maxima_objetiva   85.7
minima_redacao     0.0
maxima_redacao   100.0
minima_comp1       0.0
maxima_comp1      60.0
minima_comp2       0.0
maxima_comp2      20.0
minima_comp3       0.0
maxima_comp3      20.0
minima_comp4       0.0
maxima_comp4       0.0
minima_comp5       0.0
maxima_comp5       0.0

### 28.contar valores ausentes

In [32]:
expressoes_nulos = []

for variavel in variaveis_1998:
    coluna = citar_identificador(variavel)

    expressoes_nulos.append(
        f"""
        COUNT(*) FILTER (
            WHERE {coluna} IS NULL
        ) AS {coluna}
        """
    )

consulta_nulos = f"""
SELECT
    {", ".join(expressoes_nulos)}

FROM enem_1998_pa_tipado
"""

nulos = conexao.execute(
    consulta_nulos
).df()

nulos_vertical = (
    nulos
    .T
    .reset_index()
)

nulos_vertical.columns = [
    "variavel",
    "quantidade_nulos",
]

nulos_vertical[
    nulos_vertical["quantidade_nulos"] > 0
]

                 variavel  quantidade_nulos
9                CO_PROVA                40
16  TX_RESPOSTAS_OBJETIVA                40
17   TX_GABARITO_OBJETIVA                40

### 29.contar valores ausentes

In [37]:
validacao_redacao = conexao.execute(
    """
    SELECT
        COUNT(*) AS total_registros,

        COUNT(*) FILTER (
            WHERE ABS(
                NU_NOTA_REDACAO
                - (
                    COALESCE(NU_NOTA_COMP1, 0)
                    + COALESCE(NU_NOTA_COMP2, 0)
                    + COALESCE(NU_NOTA_COMP3, 0)
                    + COALESCE(NU_NOTA_COMP4, 0)
                    + COALESCE(NU_NOTA_COMP5, 0)
                )
            ) > 0.000001
        ) AS notas_divergentes

    FROM enem_1998_pa_tipado
    """
).df()

validacao_redacao.T

                     0
total_registros    288
notas_divergentes    0

### 30.contar valores ausentes

In [38]:
valores_comp45 = conexao.execute(
    """
    SELECT
        NU_NOTA_COMP4,
        NU_NOTA_COMP5,
        COUNT(*) AS quantidade

    FROM enem_1998_pa_tipado

    GROUP BY
        NU_NOTA_COMP4,
        NU_NOTA_COMP5

    ORDER BY quantidade DESC
    """
).df()

valores_comp45.T

                   0
NU_NOTA_COMP4    0.0
NU_NOTA_COMP5    0.0
quantidade     288.0

### 31.contar valores ausentes

In [39]:
situacao_redacao = conexao.execute(
    """
    SELECT
        TP_STATUS_REDACAO,
        COUNT(*) AS quantidade,
        MIN(NU_NOTA_REDACAO) AS nota_minima,
        MAX(NU_NOTA_REDACAO) AS nota_maxima

    FROM enem_1998_pa_tipado

    GROUP BY TP_STATUS_REDACAO
    ORDER BY quantidade DESC
    """
).df()

situacao_redacao.T

                       0    1
TP_STATUS_REDACAO      P    F
quantidade           248   40
nota_minima          0.0  0.0
nota_maxima        100.0  0.0

### 32.contar valores ausentes

In [36]:
arquivo_dicionario = (
    PROJECT_ROOT
    / "data"
    / "metadata"
    / "dicionarios"
    / "dicionario_enem_1998.xlsx"
)

excel_dicionario = pd.ExcelFile(
    arquivo_dicionario
)

excel_dicionario.sheet_names

['MICRODADOS_ENEM_1998']

### 33.cruzar presença e situação da redação

In [41]:
cruzamento_presenca = conexao.execute(
    """
    SELECT
        TP_PRESENCA,
        TP_STATUS_REDACAO,
        COUNT(*) AS quantidade,

        COUNT(*) FILTER (
            WHERE CO_PROVA IS NULL
        ) AS co_prova_nulo,

        COUNT(*) FILTER (
            WHERE TX_RESPOSTAS_OBJETIVA IS NULL
        ) AS respostas_nulas,

        COUNT(*) FILTER (
            WHERE TX_GABARITO_OBJETIVA IS NULL
        ) AS gabaritos_nulos

    FROM enem_1998_pa_tipado

    GROUP BY
        TP_PRESENCA,
        TP_STATUS_REDACAO

    ORDER BY
        TP_PRESENCA,
        TP_STATUS_REDACAO
    """
).df()

cruzamento_presenca

,TP_PRESENCA,TP_STATUS_REDACAO,quantidade,co_prova_nulo,respostas_nulas,gabaritos_nulos
0,0,F,40,40,40,40
1,1,P,248,0,0,0

### 34.definir o destino Silver

In [49]:
SILVER_DIR = (
    PROJECT_ROOT
    / "data"
    / "silver"
    / "microdados_selecionados"
)

diretorio_silver = (
    SILVER_DIR
    / f"ano={ano_teste}"
    / "uf=PA"
)

arquivo_parquet = (
    diretorio_silver
    / f"enem_PA_{ano_teste}.parquet"
)

print(f"Diretório: {diretorio_silver}")
print(f"Parquet  : {arquivo_parquet}")

Diretório: /home/akel/PycharmProjects/ENEM/data/silver/microdados_selecionados/ano=1998/uf=PA
Parquet  : /home/akel/PycharmProjects/ENEM/data/silver/microdados_selecionados/ano=1998/uf=PA/enem_PA_1998.parquet

### 35.preparar o diretório

In [50]:
diretorio_silver.mkdir(
    parents=True,
    exist_ok=True,
)

if arquivo_parquet.exists():
    raise FileExistsError(
        f"O arquivo já existe: {arquivo_parquet}"
    )

print("Destino disponível para gravação.")

Destino disponível para gravação.

### 36.gravar o Parquet

In [51]:
caminho_parquet_sql = str(
    arquivo_parquet
).replace("'", "''")

conexao.execute(
    f"""
    COPY (
        SELECT *
        FROM enem_1998_pa_tipado
    )
    TO '{caminho_parquet_sql}'
    (
        FORMAT PARQUET,
        COMPRESSION ZSTD
    )
    """
)

print(f"Parquet gravado: {arquivo_parquet}")

Parquet gravado: /home/akel/PycharmProjects/ENEM/data/silver/microdados_selecionados/ano=1998/uf=PA/enem_PA_1998.parquet

### 37 — verificar o arquivo

In [52]:
if not arquivo_parquet.exists():
    raise FileNotFoundError(
        "O Parquet não foi criado."
    )

tamanho_parquet_mb = (
    arquivo_parquet.stat().st_size
    / 1024**2
)

print(f"Tamanho: {tamanho_parquet_mb:.4f} MB")

Tamanho: 0.0156 MB

### 38 — validar estrutura e quantidade

In [55]:
validacao_parquet = conexao.execute(
    f"""
    SELECT
        COUNT(*) AS total_linhas,
        COUNT(*) - COUNT(DISTINCT NU_INSCRICAO)
            AS duplicacoes,
        COUNT(*) FILTER (
            WHERE SG_UF_RESIDENCIA <> 'PA'
        ) AS outras_ufs,
        MIN(NU_ANO) AS menor_ano,
        MAX(NU_ANO) AS maior_ano

    FROM read_parquet(
        '{caminho_parquet_sql}',
        hive_partitioning = false
    )
    """
).df()

validacao_parquet.T

                 0
total_linhas   288
duplicacoes      0
outras_ufs       0
menor_ano     1998
maior_ano     1998

### 39 — comparar origem e Parquet

In [56]:
comparacao = conexao.execute(
    f"""
    SELECT COUNT(*) AS quantidade_diferencas

    FROM (
        (
            SELECT *
            FROM enem_1998_pa_tipado

            EXCEPT ALL

            SELECT *
            FROM read_parquet(
                '{caminho_parquet_sql}',
                hive_partitioning = false
            )
        )

        UNION ALL

        (
            SELECT *
            FROM read_parquet(
                '{caminho_parquet_sql}',
                hive_partitioning = false
            )

            EXCEPT ALL

            SELECT *
            FROM enem_1998_pa_tipado
        )
    )
    """
).df()

comparacao.T

                       0
quantidade_diferencas  0

### 40. Teste final do particionamento Hive

In [57]:
caminho_silver_glob = str(
    SILVER_DIR / "**" / "*.parquet"
).replace("'", "''")

consulta_particoes = conexao.execute(
    f"""
    SELECT
        ano,
        uf,
        COUNT(*) AS quantidade

    FROM read_parquet(
        '{caminho_silver_glob}',
        hive_partitioning = true
    )

    GROUP BY
        ano,
        uf

    ORDER BY
        ano,
        uf
    """
).df()

consulta_particoes

    ano  uf  quantidade
0  1998  PA         288

In [58]:
conexao.close()

print("Conexão DuckDB encerrada.")

Conexão DuckDB encerrada.